//Project Euler: Problem 29: Distinct powers

//How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ n and 2 ≤ b ≤ n?
//Solution
function distinctPowers(n) {
    let list = [];
    for (let a = 2; a <= n; a++) {
        for (let b = 2; b <= n; b++) {
            let term = Math.pow(a, b);
            if (list.indexOf(term) === -1) list.push(term);
        }
    }
    return list.length;
}

distinctPowers(30);