#Project Euler: Problem 2: Even Fibonacci Numbers
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed nth term, find the sum of the even-valued terms.

#Solution:

function fiboEvenSum(n) {
  var sum=2,i,a=1,b=2,c;
  for(i=2; i<=n; i++){
    c=a+b;
    if(c%2==0){
      sum+=c;
    }
    a=b;
    b=c;
  }
  return sum;
}

fiboEvenSum(10);